### ISSUE TITLE
Upgrade ReadTheDocs YAML

### ISSUE THREAD

**Issue by zuoxingdong** [zuoxingdong/lagom#38]
```
# .readthedocs.yml

version: 2

python:
  version: 3.7
  install:
     - method: pip
       path: .
```
